project 'garagecoders.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'garagecoders' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for garagecoders
  
  pod 'Moya', '~> 13.0'

  target 'garagecodersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'garagecodersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
